// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Tbv1ynEDhZFvICC0IquJagZcTzamsH4',
    appId: '1:748342580441:web:18275dc08047a265f39ac8',
    messagingSenderId: '748342580441',
    projectId: 'mmmm-74a58',
    authDomain: 'mmmm-74a58.firebaseapp.com',
    storageBucket: 'mmmm-74a58.appspot.com',
    measurementId: 'G-C43ZG7EXX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoM8yIyD76agwBtixPYEi-fv1A64Jp5sc',
    appId: '1:748342580441:android:4aefaecbdacb29d0f39ac8',
    messagingSenderId: '748342580441',
    projectId: 'mmmm-74a58',
    storageBucket: 'mmmm-74a58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJ9jEgmsj1UgN7gq2mHTIo1nRQ03uxfA',
    appId: '1:748342580441:ios:c7fcf589dc8ac04df39ac8',
    messagingSenderId: '748342580441',
    projectId: 'mmmm-74a58',
    storageBucket: 'mmmm-74a58.appspot.com',
    iosBundleId: 'com.example.socialapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJ9jEgmsj1UgN7gq2mHTIo1nRQ03uxfA',
    appId: '1:748342580441:ios:75036e8710b54ee5f39ac8',
    messagingSenderId: '748342580441',
    projectId: 'mmmm-74a58',
    storageBucket: 'mmmm-74a58.appspot.com',
    iosBundleId: 'com.example.socialapp2.RunnerTests',
  );
}
